### ISSUE TITLE
Aspect ratio has to be 1.0

### ISSUE THREAD

**Issue by matthewturk** [yt-project/yt_idv#56]
There seems to be an assumption somewhere in the code that the aspect ratio is 1.0 when creating or drawing things, specifically the volume rendering.

**Comment by matthewturk** [comment]
to be clear, this should not be the case, and it can be seen by changing the width to anything other than the height in `amr_volume_rendering.py`.

**Comment by chrishavlin** [comment]
Fixed in #57 !
